name: 'Conan Upload'
description: 'Uploads conan package to given remote'

inputs:
  package_name:
    description: Name of conan package to build
    required: true
    type: string
  remote_url:
    description: URL of remote to deploy package to
    required: true
    type: string
  user:
    description: Name of user allowed to deploy the package
    required: true
    type: string
  password:
    description: Password for user allowed to deploy the package
    required: true
    type: string
  options:
    description: Additional arguments passed to conan
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - id: conan
      uses: turtlebrowser/get-conan@v1.2
    - run: conan remote add GITHUB_ACTIONS_TEMP_REMOTE ${{ inputs.remote_url }}
      shell: bash
    - run: conan remote login GITHUB_ACTIONS_TEMP_REMOTE ${{ inputs.user }} -p ${{ inputs.password }}
      shell: bash
    - run: conan upload -r GITHUB_ACTIONS_TEMP_REMOTE ${{ inputs.package_name }} ${{ inputs.options }}
      shell: bash
    - run: |
        conan remote remove GITHUB_ACTIONS_TEMP_REMOTE
        conan user -c
      shell: bash
